### ISSUE TITLE
[BUG?]: Checkpoint name has a leading underscore

### ISSUE THREAD

**Issue by Woisek** [thedyze/save-image-extended-comfyui#15]
I addressed that a long time ago on reddit, but it's still here: When using ckpt_name, the the checkpoint name gets a leading underscore, i.e. "_realistic_vision_v5.1_SD1.5"
It would be nice if this won't happen.
Also, I wonder if there is a list on what tokens we could use as placeholder, like ckpt_name, seed, steps, sampler, cfg, etc. ...

Thanks for this great save node. 👍

**Comment by Woisek** [comment]
This problem still exists ... any idea when or even if it will be addressed ... ? 😐

**Comment by Woisek** [comment]
> i fixed it [here](https://github.com/audioscavenger/save-image-extended-comfyui), update your comfy manager

Have to say, that it's not fixed for me. Still adds the underscore to the beginning. 😐
![FK8OWUFAak](https://github.com/thedyze/save-image-extended-comfyui/assets/122026301/514d17fc-8c54-454a-aecb-7a46a84cca70)
The left is a new added node after update, the right an 'old' existing one.

**Comment by audioscavenger** [comment]
again, this is fixed. you are probably 15 versions behind. this repo is abandonned anyway.

**Comment by Woisek** [comment]
> again, this is fixed. you are probably 15 versions behind. this repo is abandonned anyway.

Okay, but your 'fixed' version doesn't work at all.

Traceback (most recent call last):
  File "V:\AI_programms\ComfyUI\nodes.py", line 1866, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "V:\AI_programms\ComfyUI\custom_nodes\save-image-extended-comfyui\__init__.py", line 14, in <module>
    from .save_image_extended import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "V:\AI_programms\ComfyUI\custom_nodes\save-image-extended-comfyui\save_image_extended.py", line 14
    version = 2.6.5
                 ^^
SyntaxError: invalid syntax

Cannot import V:\AI_programms\ComfyUI\custom_nodes\save-image-extended-comfyui module for custom nodes: invalid syntax (save_image_extended.py, line 14)

So what about that then?

**Comment by audioscavenger** [comment]
> So what about that then?
very sorry yes, i forgot 2.6.5 is not a float number... i fixed it immediately but somehow you got the bug just before i pushed!
